#!/bin/sh

# Add the Nix profile to the search path of pkg-config
export PKG_CONFIG_PATH=$HOME/.nix-profile/lib/pkgconfig:$PKG_CONFIG_PATH

XTCFLAGS="$(pkg-config --variable=strcxtcflags dryad)"
STRCFLAGS="$(pkg-config --variable=strcflags dryad)"

strc -i java-typestate.str -m main-java-typestate $XTCFLAGS $STRCFLAGS --format-check -1
